version: 2.1
jobs:
  test_go:
    docker:
      - image: cimg/go:1.21.5
    steps:
      - checkout
      - run:
          name: Running go tests
          command: |
            go mod tidy
            go test -coverage ./...
