version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.21.5
    steps:
      - checkout
      - run:
          name: Running go tests
          command: |
            go mod tidy
            go mod download
            go test -coverage ./...
